### ISSUE TITLE
MobilityDB

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-movingfeatures#2]
This issue provides a forum to evaluate and discuss [MobilityDB](https://github.com/MobilityDB/MobilityDB) for potential relevance to this API.

**Comment by mahmsakr** [comment]
MobilityDB implements a novel data model of moving features called the sequence representation, described [here](https://docs.mobilitydb.com/pub/TODS.pdf).

![MobilityDBDataModel](https://user-images.githubusercontent.com/47746017/128679101-33a23ae2-4df7-477d-9cc1-66590beed6e2.png)

**Comment by mahmsakr** [comment]
The MobilityDB [API](https://docs.mobilitydb.com/MobilityDB/develop/apa.html)
