### ISSUE TITLE
Inconsistency in OpenAPI version referenced

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-movingfeatures#57]
[Clause 3](https://opengeospatial.github.io/ogcna-auto-review/22-003.html) of the draft version of OGC API - Moving Features - Part 1: Core 1.0.0 currently normatively references OpenAPI 3.1.0, however it is also designed to be an extension of OGC API - Features - Part 1: Core 1.0.1 which references OpenAPI 3.0.3. 

For consistency, OGC API - Moving Features - Part 1: Core should also reference OpenAPI 3.0.3.

**Comment by TaehoonK** [comment]
@ghobona, thank you for noticing this detail. 
I updated that part once before, but I missed it. 
I'll make sure to fix that.
