### ISSUE TITLE
Mandatory conformance classes for compliance

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-movingfeatures#66]
“The conformance classes for OGC API — Moving Features are:

* Collection Catalog
* Moving Features
* Common Requirements

The conformance class defines the minimum requirements for an API to be compliant with the OGC API — Moving Features Standard. “

So it is unclear which conformance class the text is referring to when it says “The conformance class defines the…”.

My guess is that all of the three conformance classes are required for an API to be declared compliant to OGC API - Moving Features. 

@TaehoonK could you please confirm whether all three conformance classes are required for an API to be declared compliant to the Standard?

**Comment by TaehoonK** [comment]
@ghobona Yes, all three conformance classes (Collection Catalog, Moving Features, and Common Requirements) are mandatory.
